#!/bin/bash

########################################################################
#   Compiles dynarray.cpp and main.cpp into the executable 'arraytest' #
########################################################################

set -e    # halt on first error

# use 'clang++' as the compiler
CPP=clang++

# be aggressive about warnings and errors
FLAGS="-g -Wall -Wextra -Werror -Wfatal-errors -std=c++11 -pedantic"

# clear out old object files
rm -f *.o

# compile

$CPP $FLAGS -o arraytest dynarray.cpp main.cpp